### ISSUE TITLE
Razor support

### ISSUE THREAD

**Issue by Spidermain50** [JaimeStill/nocturnal#1]
Razor code doesn't appear to be included in the style scope. Is that by design?

**Comment by JaimeStill** [comment]
Which theme are you using, Nocturnal, or Nocturnal Minimal? They are highlighting fine in both Razor and Blazor for me. The minimal theme isn't going to have a lot of syntax highlighting by design.

**Comment by Spidermain50** [comment]
I was referring to the @if statements of the code and, after looking at some other themes for comparison, am now seeing that no theme styles that portion of the code.

**Comment by JaimeStill** [comment]
Maybe check out [Razor+](https://marketplace.visualstudio.com/items?itemName=austincummings.razor-plus)
